/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication8;

import javax.swing.JOptionPane;

/**
 *
 * @author Nick
 */
public class Conversor extends javax.swing.JFrame {

    /**
     * Creates new form Conversor
     */
    public Conversor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtMonto = new javax.swing.JTextField();
        txtMoneda = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btn_convert = new javax.swing.JButton();
        txtAMoneda = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Cantidad");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, 40));
        jPanel1.add(jtxtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 282, -1));

        txtMoneda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PESOS", "USD", "EURO" }));
        jPanel1.add(txtMoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 282, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Moneda $");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        btn_convert.setText("Convertir");
        btn_convert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_convertActionPerformed(evt);
            }
        });
        jPanel1.add(btn_convert, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 282, 53));

        txtAMoneda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "USD", "EURO", "PESOS" }));
        jPanel1.add(txtAMoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 282, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Convertir a");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/conversor/Images/R (1).jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -20, 860, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_convertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_convertActionPerformed
        // TODO add your handling code here:
        double resultado;
        double monto = Double.parseDouble(jtxtMonto.getText());
//FROM = txtMoneda
//to = txtAMoneda
if(txtMoneda.getSelectedItem().toString() == "USD" && txtAMoneda.getSelectedItem().toString() == "PESOS")

{
    resultado = monto * 1000;
    JOptionPane.showMessageDialog(this, "La cantidad es: "+ resultado + " Pesos");

}else if(txtMoneda.getSelectedItem().toString() == "PESOS" && txtAMoneda.getSelectedItem().toString() == "USD")

{
    resultado =  monto * 0.0011;
    JOptionPane.showMessageDialog(this, "La cantidad es: "+ resultado + " Dolares");

}
else if(txtMoneda.getSelectedItem().toString() == "USD" && txtAMoneda.getSelectedItem().toString() == "EURO")

{resultado =  monto * 1.07 ;
JOptionPane.showMessageDialog(this, "La cantidad es: "+ resultado + " Euros");}
else if(txtMoneda.getSelectedItem().toString() == "EURO" && txtAMoneda.getSelectedItem().toString() == "USD")

{resultado =  monto * 0.94 ;
    JOptionPane.showMessageDialog(this, "La cantidad es: "+ resultado + " Dolares");}

else if(txtMoneda.getSelectedItem().toString() == "PESOS" && txtAMoneda.getSelectedItem().toString() == "EURO")

{resultado =  monto / 925.93 ;
    JOptionPane.showMessageDialog(this, "La cantidad es: "+ resultado + " Euros");}
else if(txtMoneda.getSelectedItem().toString() == "EURO" && txtAMoneda.getSelectedItem().toString() == "PESOS")

{resultado =  monto  * 925.93 ;
    JOptionPane.showMessageDialog(this, "La cantidad es: "+ resultado + " Pesos");}
else {


JOptionPane.showMessageDialog(this, "1 = 1 Es el mismo valor");
}











    }//GEN-LAST:event_btn_convertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conversor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_convert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtxtMonto;
    private javax.swing.JComboBox<String> txtAMoneda;
    private javax.swing.JComboBox<String> txtMoneda;
    // End of variables declaration//GEN-END:variables
}
